### ISSUE TITLE
System.IO.IOException: Function not implemented on M1 Mac

### ISSUE THREAD

**Issue by wongelz** [aaronpowell/httpstatus#111]
Hi there, running the latest docker image on an M1 Mac crashes with the following logs:

```
❯ docker run ghcr.io/aaronpowell/httpstatus:a5cde3654593eee582ac1071623a82dfa2b53408
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Unhandled exception. System.IO.IOException: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.Add[TSource](IConfigurationBuilder builder, Action`1 configureSource)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, IFileProvider provider, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass11_0.<ConfigureDefaults>b__1(HostBuilderContext hostingContext, IConfigurationBuilder config)
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at Teapot.Web.Program.Main(String[] args) in /src/Teapot.Web/Program.cs:line 14
qemu: uncaught target signal 6 (Aborted) - core dumped
```

**Comment by aaronpowell** [comment]
I'm not overly surprised it doesn't work, the builds are not for arm64.

I've got no access to a M1 Mac, so I'm not sure how to test/build an M1 compatibe image. Are you able to build on your Mac using the dockerfile at https://github.com/aaronpowell/httpstatus/blob/main/src/Teapot.Web/Dockerfile and run it locally?

**Comment by wongelz** [comment]
> I'm not overly surprised it doesn't work, the builds are not for arm64.
> 
> I've got no access to a M1 Mac, so I'm not sure how to test/build an M1 compatibe image. Are you able to build on your Mac using the dockerfile at https://github.com/aaronpowell/httpstatus/blob/main/src/Teapot.Web/Dockerfile and run it locally?

That worked :) Maybe all that's needed is cross-compilation - https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/

**Comment by aaronpowell** [comment]
Try pulling `latest` again, I've just pushed a change that should do multi-platform builds and it should've pushed a multi-platform build.

**Comment by RobFaie** [comment]
Working for me on an M1 Pro.

**Comment by wongelz** [comment]
Working for me too. Thanks for your help.

**Comment by aaronpowell** [comment]
well, that was easier than expected!

Thanks @wongelz and @RobFaie
